INSERT INTO cshop.product_type(name) VALUES ('Видеокарты');
INSERT INTO cshop.product_type(name) VALUES ('Процессоры');
INSERT INTO cshop.product_type(name) VALUES ('Материские платы');
INSERT INTO cshop.product_type(name) VALUES ('Оперативная память');
INSERT INTO cshop.product_type(name) VALUES ('Кулеры');
INSERT INTO cshop.product_type(name) VALUES ('SSD');
INSERT INTO cshop.product_type(name) VALUES ('Жесткие диски');
INSERT INTO cshop.product_type(name) VALUES ('Корпуса');
INSERT INTO cshop.product_type(name) VALUES ('Блоки питания');
INSERT INTO cshop.product_type(name) VALUES ('Звуковые карты');
INSERT INTO cshop.product_type(name) VALUES ('Сетевые адаптеры');
INSERT INTO cshop.product_type(name) VALUES ('Оптические накопители');

INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS Radeon RX 560 EVO OC Edition 4GB GDDR5', 'частота ядра 1149 МГц/1187 МГц, 896sp, частота памяти 1500 МГц, 128 бит, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\ASUS_Radeon_RX_560_EVO_OC_Edition_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI Radeon RX 580 Armor 8GB GDDR5', 'частота ядра 1340 МГц, 2304sp, частота памяти 2000 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_Radeon_RX_580_Armor_8GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI Radeon RX 580 Gaming X 4GB GDDR5', 'частота ядра 1380 МГц, 2304sp, частота памяти 1750 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_Radeon_RX_580_Gaming_X_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte Radeon RX 570 Gaming 4GB GDDR5', 'частота ядра 1244 МГц, 2048sp, частота памяти 1750 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_Radeon_RX_570_Gaming_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte Radeon RX 580 Gaming 4GB GDDR5', 'частота ядра 1340 МГц, 2304sp, частота памяти 1750 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_Radeon_RX_580_Gaming_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Sapphire Nitro+ Radeon RX 580 OC 4GB GDDR5', 'частота ядра 1411 МГц, 2304sp, частота памяти 1750 МГц, 256 бит, 6+8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\Sapphire_Nitro+_Radeon_RX_580_OC_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('AMD Radeon RX Vega 56 8G HBM2', 'частота ядра 1156 МГц/1471 МГц, 3584sp, частота памяти 800 МГц, 2048 бит, 8+8 pin, 2 слота, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\AMD_Radeon_RX_Vega_56_8G_HBM2.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI Radeon RX Vega 56 Air Boost OC 8GB HBM2', 'частота ядра 1181 МГц/1520 МГц, 3584sp, частота памяти 800 МГц, 2048 бит, 8+8 pin, 2 слота, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_Radeon_RX_Vega_56_Air_Boost_OC_8GB_HBM2.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI Radeon RX Vega 64 Iron 8GB HBM2', 'частота ядра 1247 МГц/1546 МГц, 4096sp, частота памяти 945 МГц, 2048 бит, 8+8 pin, 2 слота, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_Radeon_RX_Vega_64_Iron_8GB_HBM2.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI GeForce GTX 1070 Ti Aero 8GB GDDR5', 'частота ядра 1607 МГц/1683 МГц, 2432sp, частота памяти 2002 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_GeForce_GTX_1070_Ti_Aero_8GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte GeForce GTX 1080 Ti Turbo 11GB GDDR5X', 'частота ядра 1480 МГц/1582 МГц, 3584sp, частота памяти 2752 МГц, 352 бит, 6+8 pin, 2.5 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_GeForce_GTX_1080_Ti_Turbo_11GB_GDDR5X.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI GeForce GTX 1050 Ti Aero ITX OCV1 4GB GDDR5', 'частота ядра 1341 МГц/1455 МГц, 768sp, частота памяти 1752 МГц, 128 бит, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_GeForce_GTX_1050_Ti_Aero_ITX_OCV1_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS Turbo GeForce GTX 1070 Ti 8GB GDDR5', 'частота ядра 1607 МГц/1683 МГц, 2432sp, частота памяти 2002 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\ASUS_Turbo_GeForce_GTX_1070_Ti_8GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte GeForce GTX 1080 Mini ITX 8GB GDDR5X', 'частота ядра 1607 МГц/1733 МГц, 2560sp, частота памяти 2502 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_GeForce_GTX_1080_Mini_ITX_8GB_GDDR5X.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS GeForce GTX 1080 Ti Founders Edition 11GB GDDR5X', 'частота ядра 1480 МГц/1582 МГц, 3584sp, частота памяти 2752 МГц, 352 бит, 6+8 pin, 2 слота, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\ASUS_GeForce_GTX_1080_Ti_Founders_Edition_11GB_GDDR5X.jpeg'), 1);

INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Intel Core i7-8700K', 'Coffee Lake, LGA1151 v2, 6 ядер, частота 4.7/3.7 ГГц, кэш 12 МБ, техпроцесс 14 нм, TDP 95W', lo_import('E:\projects\maven-projects\CShop\products\Intel_Core_i7-8700K.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Intel Core i5-8600K', 'Coffee Lake, LGA1151 v2, 6 ядер, частота 4.3/3.6 ГГц, кэш 9 МБ, техпроцесс 14 нм, TDP 95W', lo_import('E:\projects\maven-projects\CShop\products\Intel_Core_i5-8600K.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Intel Core i3-8350K', 'Coffee Lake, LGA1151 v2, 4 ядра, частота 4 ГГц, кэш 8 МБ, техпроцесс 14 нм, TDP 91W', lo_import('E:\projects\maven-projects\CShop\products\Intel_Core_i3-8350K.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Intel Core i5-8500', 'Coffee Lake, LGA1151 v2, 6 ядер, частота 4.1/3 ГГц, кэш 9 МБ, техпроцесс 14 нм, TDP 65W', lo_import('E:\projects\maven-projects\CShop\products\Intel_Core_i5-8600K.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Intel Core i9-7900X', 'Skylake-X, LGA2066, 10 ядер, частота 4.3/3.3 ГГц, кэш 13 МБ, техпроцесс 14 нм, TDP 140W', lo_import('E:\projects\maven-projects\CShop\products\Intel_Core_i9_7900x.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('AMD Ryzen Threadripper 1950X', 'Whitehaven, TR4, 16 ядер, частота 4/3.4 ГГц, кэш 8 Мб + 32 МБ, техпроцесс 14 нм, TDP 180W', lo_import('E:\projects\maven-projects\CShop\products\Ryzen-Threadripper-1950X.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('AMD Ryzen 7 2700X', 'Pinnacle Ridge, AM4, 8 ядер, частота 4.3/3.7 ГГц, кэш 4 Мб + 16 МБ, техпроцесс 12 нм, TDP 105W', lo_import('E:\projects\maven-projects\CShop\products\AMD_Ryzen_7_2700X.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('AMD Ryzen 5 1600X', 'Summit Ridge, AM4, 6 ядер, частота 4/3.6 ГГц, кэш 3 Мб + 16 МБ, техпроцесс 14 нм, TDP 95W', lo_import('E:\projects\maven-projects\CShop\products\AMD_Ryzen_5_1600X.jpg'), 1);

INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS ROG Strix B360-G Gaming', 'mATX, сокет Intel LGA1151 v2, чипсет Intel B360, память 4xDDR4, слоты: 2xPCIe x16, 2xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\ASUS_ROG_Strix_B360-G_Gaming.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS Prime Z370-A', 'ATX, сокет Intel LGA1151 v2, чипсет Intel Z370, память 4xDDR4, слоты: 3xPCIe x16, 4xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\ASUS_Prime_Z370-A.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS ROG Strix B360-I Gaming', 'Mini-ITX, сокет Intel LGA1151 v2, чипсет Intel B360, память 2xDDR4, слоты: 1xPCIe x16', lo_import('E:\projects\maven-projects\CShop\products\ASUS_ROG_Strix_B360-I_Gaming.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS TUF X299 Mark 1', 'ATX, сокет Intel LGA2066, чипсет Intel X299, память 8xDDR4, слоты: 3xPCIe x16, 2xPCIe x4', lo_import('E:\projects\maven-projects\CShop\products\ASUS_TUF_X299_Mark_1.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS ROG Strix H370-I Gaming', 'Mini-ITX, сокет Intel LGA1151 v2, чипсет Intel H370, память 2xDDR4, слоты: 1xPCIe x16', lo_import('E:\projects\maven-projects\CShop\products\ASUS_ROG_Strix_H370-I_Gaming.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS ROG Crosshair VII Hero', 'ATX, сокет AMD AM4, чипсет AMD X470, память 4xDDR4, слоты: 3xPCIe x16, 2xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\ASUS_ROG_Crosshair_VII_Hero.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte X470 Aorus Gaming 7 WiFi (rev. 1.0)', 'ATX, сокет AMD AM4, чипсет AMD X470, память 4xDDR4, слоты: 3xPCIe x16, 2xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_X470_Aorus_Gaming_7_WiFi_(rev._1.0).jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte X399 AORUS Gaming 7 (rev. 1.0)', 'ATX, сокет AMD TR4, чипсет AMD X399, память 8xDDR4, слоты: 5xPCIe x16', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_X399_AORUS_Gaming_7_(rev._1.0).jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte H370 Aorus Gaming 3 WiFi (rev. 1.0)', 'ATX, сокет Intel LGA1151 v2, чипсет Intel H370, память 4xDDR4, слоты: 2xPCIe x16, 4xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_H370_Aorus_Gaming_3_WiFi_(rev._1.0).png'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI Z370 Gaming Plus', 'ATX, сокет Intel LGA1151 v2, чипсет Intel Z370, память 4xDDR4, слоты: 2xPCIe x16, 4xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\MSI_Z370_Gaming_Plus.png'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI X299 Gaming M7 ACK', 'ATX, сокет Intel LGA2066, чипсет Intel X299, память 8xDDR4, слоты: 4xPCIe x16, 2xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\MSI_X299_Gaming_M7_ACK.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI X299 Raider', 'ATX, сокет Intel LGA2066, чипсет Intel X299, память 8xDDR4, слоты: 4xPCIe x16, 1xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\MSI_X299_Raider.png'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI Z370 SLI Plus', 'ATX, сокет Intel LGA1151 v2, чипсет Intel Z370, память 4xDDR4, слоты: 3xPCIe x16, 3xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\MSI_Z370_SLI_Plus.png'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI B350M Gaming PRO', 'mATX, сокет AMD AM4, чипсет AMD B350, память 2xDDR4, слоты: 1xPCIe x16, 2xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\MSI_B350M_Gaming_PRO.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('BIOSTAR H110MHV3 Ver. 7.x', 'mATX, сокет Intel LGA1151, чипсет Intel H110, память 2xDDR3, слоты: 1xPCIe x16, 1xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\BIOSTAR_H110MHV3_Ver._7.x.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('BIOSTAR TB250-BTC PRO Ver. 6.x', 'ATX, сокет Intel LGA1151, чипсет Intel B250, память 2xDDR4, слоты: 1xPCIe x16, 11xPCIe x1', lo_import('E:\projects\maven-projects\CShop\products\BIOSTAR_TB250-BTC_PRO_Ver. 6.x.jpeg'), 1);

INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Crucial 8GB DDR4 PC4-19200 [CT8G4DFD824A]', '1 модуль, частота 2400 МГц, CL 17T, напряжение 1.2 В', lo_import('E:\projects\maven-projects\CShop\products\Crucial_8GB_DDR4_PC4-19200_[CT8G4DFD824A].jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Crucial Ballistix Tactical 8GB DDR4 PC4-24000 [BLT8G4D30AETA]', '1 модуль, частота 3000 МГц, CL 15T, тайминги 15-16-16, напряжение 1.35 В', lo_import('E:\projects\maven-projects\CShop\products\Crucial_Ballistix_Tactical_8GB_DDR4_PC4-24000_[BLT8G4D30AETA].jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Crucial Ballistix Sport LT White 16GB DDR4 PC4-19200 [BLS16G4D240FSC]', '1 модуль, частота 2400 МГц, CL 16T, тайминги 16-16-16, напряжение 1.2 В', lo_import('E:\projects\maven-projects\CShop\products\Crucial_Ballistix_Sport_LT_White_16GB_DDR4_PC4-19200_[BLS16G4D240FSC].jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('HyperX Fury Blue 4GB DDR3 PC3-12800 HX316C10F/4', '1 модуль, частота 1600 МГц, CL 10T, тайминги 10-10-10, напряжение 1.5 В', lo_import('E:\projects\maven-projects\CShop\products\HyperX_Fury_Blue_4GB_DDR3_PC3-12800_HX316C10F-4.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('HyperX Savage 8GB DDR3 PC3-12800 HX316C9SR/8', '1 модуль, частота 1600 МГц, CL 9T, тайминги 9-9-9, напряжение 1.5 В', lo_import('E:\projects\maven-projects\CShop\products\HyperX_Savage_8GB_DDR3_PC3-12800_HX316C9SR-8.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('HyperX Fury 16GB DDR4 PC4-19200 HX424C15FB/16', '1 модуль, частота 2400 МГц, CL 15T, тайминги 15-15-15, напряжение 1.2 В', lo_import('E:\projects\maven-projects\CShop\products\HyperX_Fury_16GB_DDR4_PC4-19200_HX424C15FB-16.jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Patriot Signature Line 8GB DDR3 PC3-12800 [PSD38G16002H]', '1 модуль, частота 1600 МГц, CL 11T, напряжение 1.5 В', lo_import('E:\projects\maven-projects\CShop\products\Patriot_Signature_Line_8GB_DDR3_PC3-12800_[PSD38G16002H].jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Patriot 4GB DDR3 PC3-12800 [PSD34G1600L81]', '1 модуль, частота 1600 МГц, напряжение 1.35 В', lo_import('E:\projects\maven-projects\CShop\products\Patriot_4GB_DDR3_PC3-12800_[PSD34G1600L81].jpg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Patriot Signature Line 8GB DDR4 PC4-21300 PSD48G266681H', '1 модуль, частота 2666 МГц, CL 19T, тайминги 19-19-19-43, напряжение 1.2 В', lo_import('E:\projects\maven-projects\CShop\products\Patriot_Signature_Line_8GB_DDR4_PC4-21300_PSD48G266681H.jpg'), 1);

INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('', '', lo_import('E:\projects\maven-projects\CShop\products\'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('', '', lo_import('E:\projects\maven-projects\CShop\products\'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('', '', lo_import('E:\projects\maven-projects\CShop\products\'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('', '', lo_import('E:\projects\maven-projects\CShop\products\'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('', '', lo_import('E:\projects\maven-projects\CShop\products\'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('', '', lo_import('E:\projects\maven-projects\CShop\products\'), 1);




INSERT INTO cshop.provider (name) VALUES ('ООО «Компания МИПС плюс»');
INSERT INTO cshop.provider (name) VALUES ('ООО «ТрайдексБелПлюс»');
INSERT INTO cshop.provider (name) VALUES ('ООО «ДЕЛОВЫЕ ТЕХНОЛОГИИ»');
