INSERT INTO cshop.product_type(name) VALUES ('Видеокарты');
INSERT INTO cshop.product_type(name) VALUES ('Процессоры');
INSERT INTO cshop.product_type(name) VALUES ('Материские платы');
INSERT INTO cshop.product_type(name) VALUES ('Оперативная память');
INSERT INTO cshop.product_type(name) VALUES ('Кулеры');
INSERT INTO cshop.product_type(name) VALUES ('SSD');
INSERT INTO cshop.product_type(name) VALUES ('Жесткие диски');
INSERT INTO cshop.product_type(name) VALUES ('Корпуса');
INSERT INTO cshop.product_type(name) VALUES ('Блоки питания');
INSERT INTO cshop.product_type(name) VALUES ('Звуковые карты');
INSERT INTO cshop.product_type(name) VALUES ('Сетевые адаптеры');
INSERT INTO cshop.product_type(name) VALUES ('Оптические накопители');

INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS Radeon RX 560 EVO OC Edition 4GB GDDR5', 'частота ядра 1149 МГц/1187 МГц, 896sp, частота памяти 1500 МГц, 128 бит, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\ASUS_Radeon_RX_560_EVO_OC_Edition_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI Radeon RX 580 Armor 8GB GDDR5', 'частота ядра 1340 МГц, 2304sp, частота памяти 2000 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_Radeon_RX_580_Armor_8GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI Radeon RX 580 Gaming X 4GB GDDR5', 'частота ядра 1380 МГц, 2304sp, частота памяти 1750 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_Radeon_RX_580_Gaming_X_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte Radeon RX 570 Gaming 4GB GDDR5', 'частота ядра 1244 МГц, 2048sp, частота памяти 1750 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_Radeon_RX_570_Gaming_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte Radeon RX 580 Gaming 4GB GDDR5', 'частота ядра 1340 МГц, 2304sp, частота памяти 1750 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_Radeon_RX_580_Gaming_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Sapphire Nitro+ Radeon RX 580 OC 4GB GDDR5', 'частота ядра 1411 МГц, 2304sp, частота памяти 1750 МГц, 256 бит, 6+8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\Sapphire_Nitro+_Radeon_RX_580_OC_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('AMD Radeon RX Vega 56 8G HBM2', 'частота ядра 1156 МГц/1471 МГц, 3584sp, частота памяти 800 МГц, 2048 бит, 8+8 pin, 2 слота, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\AMD_Radeon_RX_Vega_56_8G_HBM2.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI Radeon RX Vega 56 Air Boost OC 8GB HBM2', 'частота ядра 1181 МГц/1520 МГц, 3584sp, частота памяти 800 МГц, 2048 бит, 8+8 pin, 2 слота, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_Radeon_RX_Vega_56_Air_Boost_OC_8GB_HBM2.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI Radeon RX Vega 64 Iron 8GB HBM2', 'частота ядра 1247 МГц/1546 МГц, 4096sp, частота памяти 945 МГц, 2048 бит, 8+8 pin, 2 слота, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_Radeon_RX_Vega_64_Iron_8GB_HBM2.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI GeForce GTX 1070 Ti Aero 8GB GDDR5', 'частота ядра 1607 МГц/1683 МГц, 2432sp, частота памяти 2002 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_GeForce_GTX_1070_Ti_Aero_8GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte GeForce GTX 1080 Ti Turbo 11GB GDDR5X', 'частота ядра 1480 МГц/1582 МГц, 3584sp, частота памяти 2752 МГц, 352 бит, 6+8 pin, 2.5 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_GeForce_GTX_1080_Ti_Turbo_11GB_GDDR5X.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('MSI GeForce GTX 1050 Ti Aero ITX OCV1 4GB GDDR5', 'частота ядра 1341 МГц/1455 МГц, 768sp, частота памяти 1752 МГц, 128 бит, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\MSI_GeForce_GTX_1050_Ti_Aero_ITX_OCV1_4GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS Turbo GeForce GTX 1070 Ti 8GB GDDR5', 'частота ядра 1607 МГц/1683 МГц, 2432sp, частота памяти 2002 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\ASUS_Turbo_GeForce_GTX_1070_Ti_8GB_GDDR5.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('Gigabyte GeForce GTX 1080 Mini ITX 8GB GDDR5X', 'частота ядра 1607 МГц/1733 МГц, 2560sp, частота памяти 2502 МГц, 256 бит, 8 pin, 2 слота, DVI, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\Gigabyte_GeForce_GTX_1080_Mini_ITX_8GB_GDDR5X.jpeg'), 1);
INSERT INTO cshop.product(name, description, img, product_type_id) VALUES ('ASUS GeForce GTX 1080 Ti Founders Edition 11GB GDDR5X', 'частота ядра 1480 МГц/1582 МГц, 3584sp, частота памяти 2752 МГц, 352 бит, 6+8 pin, 2 слота, HDMI, DisplayPort', lo_import('E:\projects\maven-projects\CShop\products\ASUS_GeForce_GTX_1080_Ti_Founders_Edition_11GB_GDDR5X.jpeg'), 1);

INSERT INTO cshop.provider (name) VALUES ('ООО «Компания МИПС плюс»');
INSERT INTO cshop.provider (name) VALUES ('ООО «ТрайдексБелПлюс»');
INSERT INTO cshop.provider (name) VALUES ('ООО «ДЕЛОВЫЕ ТЕХНОЛОГИИ»');
