DROP SCHEMA IF EXISTS cshop CASCADE;
CREATE SCHEMA IF NOT EXISTS cshop;
CREATE TABLE cshop.address (id BIGSERIAL NOT NULL, address CHARACTER VARYING(1024) NOT NULL, city CHARACTER VARYING(256) NOT NULL, fio CHARACTER VARYING(256) NOT NULL, phone_number CHARACTER VARYING(32) NOT NULL, postcode CHARACTER VARYING(16) NOT NULL, region CHARACTER VARYING(64) NOT NULL, PRIMARY key (id));
CREATE TABLE cshop.person (id BIGSERIAL NOT NULL, name CHARACTER VARYING(64) NOT NULL, surname CHARACTER VARYING(64) NOT NULL, patronymic CHARACTER VARYING(64), birthday TIMESTAMP NOT NULL, phone_number CHARACTER VARYING(32) NOT NULL, PRIMARY key (id));
CREATE TABLE cshop.person_addresses (person_id BIGINT NOT NULL, addresses_id BIGINT NOT NULL);
CREATE TABLE cshop.product (id BIGSERIAL NOT NULL, description CHARACTER VARYING(4096) NOT NULL, img OID NOT NULL, name CHARACTER VARYING(256) NOT NULL, product_type_id BIGINT NOT NULL, PRIMARY key (id));
CREATE TABLE cshop.product_type (id BIGSERIAL NOT NULL, name CHARACTER VARYING(64) NOT NULL, PRIMARY key (id));
CREATE TABLE cshop.provider (id BIGSERIAL NOT NULL, name CHARACTER VARYING(256) NOT NULL, PRIMARY key (id));
CREATE TABLE cshop.sale (id BIGSERIAL NOT NULL, last_update_date TIMESTAMP, sale_date TIMESTAMP, status INTEGER NOT NULL, address_id BIGINT NOT NULL, buyer_id BIGINT NOT NULL, seller_id BIGINT NOT NULL, PRIMARY key (id));
CREATE TABLE cshop.sale_products (sale_id BIGINT NOT NULL, products_id BIGINT NOT NULL);
CREATE TABLE cshop.sale_product (id BIGSERIAL NOT NULL, count INTEGER NOT NULL, supply_id BIGINT NOT NULL, PRIMARY key (id));
CREATE TABLE cshop.supply (id BIGSERIAL NOT NULL, balance INTEGER NOT NULL, count INTEGER NOT NULL, price NUMERIC(10, 2) NOT NULL, supply_price NUMERIC(10, 2) NOT NULL, product_id BIGINT NOT NULL, provider_id BIGINT NOT NULL, PRIMARY key (id));
CREATE TABLE cshop.USER (id BIGSERIAL NOT NULL, confirm BOOLEAN NOT NULL, email CHARACTER VARYING(320) NOT NULL, password CHARACTER VARYING(60) NOT NULL, role INTEGER NOT NULL, person_id BIGINT, PRIMARY key (id));
ALTER TABLE IF EXISTS cshop.product ADD CONSTRAINT uk_product_name UNIQUE (name);
ALTER TABLE IF EXISTS cshop.product_type ADD CONSTRAINT uk_product_type_name UNIQUE (name);
ALTER TABLE IF EXISTS cshop.provider ADD CONSTRAINT uk_provider_name UNIQUE (name);
ALTER TABLE IF EXISTS cshop.USER ADD CONSTRAINT uk_user_email UNIQUE (email);
ALTER TABLE IF EXISTS cshop.person_addresses ADD CONSTRAINT fk_person_addresses_addresses_id FOREIGN key (addresses_id) REFERENCES cshop.address;
ALTER TABLE IF EXISTS cshop.person_addresses ADD CONSTRAINT fk_person_addresses_person_id FOREIGN key (person_id) REFERENCES cshop.person;
ALTER TABLE IF EXISTS cshop.product ADD CONSTRAINT fk_product_product_type_id FOREIGN key (product_type_id) REFERENCES cshop.product_type;
ALTER TABLE IF EXISTS cshop.sale ADD CONSTRAINT fk_sale_address_id FOREIGN key (address_id) REFERENCES cshop.address;
ALTER TABLE IF EXISTS cshop.sale ADD CONSTRAINT fk_sale_buyer_id FOREIGN key (buyer_id) REFERENCES cshop.USER;
ALTER TABLE IF EXISTS cshop.sale ADD CONSTRAINT fk_sale_seller_id FOREIGN key (seller_id) REFERENCES cshop.USER;
ALTER TABLE IF EXISTS cshop.sale_products ADD CONSTRAINT fk_sale_products_products_id FOREIGN key (products_id) REFERENCES cshop.sale_product;
ALTER TABLE IF EXISTS cshop.sale_products ADD CONSTRAINT fk_sale_products_sale_id FOREIGN key (sale_id) REFERENCES cshop.sale;
ALTER TABLE IF EXISTS cshop.sale_product ADD CONSTRAINT fk_productsupply_id FOREIGN key (supply_id) REFERENCES cshop.supply;
ALTER TABLE IF EXISTS cshop.supply ADD CONSTRAINT fk_supply_product_id FOREIGN key (product_id) REFERENCES cshop.product;
ALTER TABLE IF EXISTS cshop.supply ADD CONSTRAINT fk_supply_provider_id FOREIGN key (provider_id) REFERENCES cshop.provider;
ALTER TABLE IF EXISTS cshop.USER ADD CONSTRAINT fk_user_person_id FOREIGN key (person_id) REFERENCES cshop.person;
